# Trajectories Analyses
Módulos de Python para analizar trayectorias de dinámica molecular

*/ Update July 2018 /*

## MDAnalysis 
from https://www.mdanalysis.org

## MDTraj
from http://mdtraj.org

## PyTraj
from https://amber-md.github.io/pytraj/latest/index.html

## Prody
from http://prody.csb.pitt.edu

# Install with conda in python 3
https://conda.io/miniconda.html
* anaconda3/bin/conda update biopython
* anaconda3/bin/conda upgrade numpy
* anaconda3/bin/pip install --upgrade pip
* anaconda3/bin/pip install prody
* anaconda3/bin/conda install ambertools=18 -c http://ambermd.org/downloads/ambertools/conda/
* anaconda3/bin/conda install mdtraj
* anaconda3/bin/conda install mdanalysis -c conda-forge
* anaconda3/bin/conda install MDAnalysisTests -c conda-forge
* anaconda3/bin/conda install nglview
* anaconda3/bin/conda install seaborn
* anaconda3/bin/pip install pbxplore
* anaconda3/bin/pip install weblogo

In [1]:
import MDAnalysis as mda
import mdtraj as mdt
import pytraj as mdp
import prody as pd

/usr/local/anaconda3/envs/Dynamics/lib/python3.8/site-packages/Bio/SubsMat/__init__.py:126: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  warnings.warn(


In [2]:
from MDAnalysis.tests.datafiles import PSF, DCD

## MDAnalysis
u = mda.Universe(PSF, DCD)

## MDTraj
t = mdt.load(DCD, top=PSF)

## PyTraj
p = mdp.load(DCD, top=PSF)

In [12]:
!pip install nglview

     |████████████████████████████████| 5.7 MB 731 kB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Using cached jupyterlab_widgets-1.0.0-py3-none-any.whl (243 kB)
  Created wheel for nglview: filename=nglview-3.0.3-py3-none-any.whl size=8057549 sha256=1bf8a2cd8b84178a44df6dfa0a00c5f6d915b3b48588fc2502fa8a12bdbfd3fe
  Stored in directory: /Users/alsalas/Library/Caches/pip/wheels/83/a4/c3/283e7ba3ea501b8fb6fb4acc8f11d6aada1f1640d794db0c41
Successfully built nglview


In [3]:
## Prody method 1
# DCD file from MDAnalysis is not recognized
q = pd.Trajectory('/Users/alsalas/GDrive/Jupyter/Dynamics/Trayectorias/run/ubq_wb_eq.dcd')
pdb = pd.parsePDB('/Users/alsalas/GDrive/Jupyter/Dynamics/Trayectorias/common/ubq_wb.pdb')
q.link(pdb)

OSError: /Users/alsalas/GDrive/Jupyter/Dynamics/Trayectorias/common/ubq_wb.pdb is not a valid filename or a valid PDB identifier.

In [4]:
## Prody method 2
ensemble = pd.parseDCD('/Users/alsalas/GDrive/Jupyter/Dynamics/Trayectorias/run/ubq_wb_eq.dcd')
structure = pd.parsePDB('/Users/alsalas/GDrive/Jupyter/Dynamics/Trayectorias/common/ubq_wb.pdb')
ensemble.setAtoms(structure)
ensemble.setCoords(structure)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/alsalas/GDrive/Jupyter/Dynamics/Trayectorias/run/ubq_wb_eq.dcd'

In [3]:
print(">>>MDAnalysis: Universe")
print(u)
print(">>>MDTraj: Trajectory")
print(t)
print(">>>MDAnalysis: Topology")
print(p)
print(">>>Prody: Ensemble")
print(ensemble)

>>>MDAnalysis: Universe
<Universe with 3341 atoms>
>>>MDTraj: Trajectory
<mdtraj.Trajectory with 98 frames, 3341 atoms, 214 residues, without unitcells>
>>>MDAnalysis: Topology
pytraj.Trajectory, 98 frames: 
Size: 0.007318 (GB)
<Topology: 3341 atoms, 214 residues, 1 mols, non-PBC>
           
>>>Prody: Ensemble


NameError: name 'ensemble' is not defined

## Vissualization Trajectory with NGLView

In [1]:
import nglview as nv
view = nv.show_pytraj(p)

# reset representation
view.representations = []
view.parameters = {'theme': 'dark'}
view.add_representation('licorice', selection='not hydrogen')
view.add_representation('cartoon')

view

NameError: name 'p' is not defined

In [15]:
%matplotlib inline

## Subset from topology

In [16]:
## MDAnalysis subset for topology
atomos   = list(u.atoms[:3])
residuos = list(u.atoms[0:100].residues)
segids   = list(u.atoms.segments)

resnames = u.atoms[0:100].residues.resnames
resids   = u.atoms[0:100].residues.resids
res_list = list(zip(resnames, resids))

import pprint
print(">>Objetos Aminoácidos")
pprint.pprint(atomos)
print(">>Objetos Residuos")
pprint.pprint(residuos)
print(">>Objetos Segmentos")
pprint.pprint(segids)

print(">>Lista de Residuos")
pprint.pprint(res_list)

>>Objetos Aminoácidos
[<Atom 1: N of type 56 of resname MET, resid 1 and segid 4AKE>,
 <Atom 2: HT1 of type 2 of resname MET, resid 1 and segid 4AKE>,
 <Atom 3: HT2 of type 2 of resname MET, resid 1 and segid 4AKE>]
>>Objetos Residuos
[<Residue MET, 1>,
 <Residue ARG, 2>,
 <Residue ILE, 3>,
 <Residue ILE, 4>,
 <Residue LEU, 5>]
>>Objetos Segmentos
[<Segment 4AKE>]
>>Lista de Residuos
[('MET', 1), ('ARG', 2), ('ILE', 3), ('ILE', 4), ('LEU', 5)]


In [17]:
## MDTraj subset for topology
topology  = t.topology
print(topology)
print('Fifth atom: %s' % topology.atom(4))
print('All atoms: %s' % [atom for atom in topology.atoms][:3])

print('Second residue: %s' % t.topology.residue(1))
print('All residues: %s' % [residue for residue in t.topology.residues][:3])

atom = topology.atom(10)
print('''Hi! I am the %sth atom, and my name is %s. 
I am a %s atom with %s bonds. 
I am part of an %s residue.''' % ( atom.index, atom.name, atom.element.name, atom.n_bonds, atom.residue.name))

<mdtraj.Topology with 1 chains, 214 residues, 3341 atoms, 3365 bonds>
Fifth atom: MET1-CA
All atoms: [MET1-N, MET1-H, MET1-H2]
Second residue: ARG2
All residues: [MET1, ARG2, ILE3]
Hi! I am the 10th atom, and my name is HG3. 
I am a hydrogen atom with 1 bonds. 
I am part of an MET residue.


In [18]:
## PyTraj subset for topology
h_indices = mdp.select_atoms(p.top, '@CA')
n_indices = mdp.select_atoms(p.top, '@N')
print(h_indices)
print(n_indices)

[   4   21   45 ... 3297 3316 3335]
[   0   19   43 ... 3295 3314 3333]


## Subset from trajectory

In [19]:
## MDAnalysis
# Subset for trajectory is a generator
print (list(u.trajectory[:3]))

for uts in u.trajectory[::20]:
    print([x for x in dir(uts) if x.startswith("_")==False])
    break

for uts in u.trajectory[::20]:    
    print("Frame: {0:5d}, Time: {1:8.3f} ps".format(uts.frame, u.trajectory.time))
    print("Rgyr: {0:g} A".format(u.atoms.radius_of_gyration()))

[< Timestep 0 with unit cell dimensions [ 0.  0.  0. 90. 90. 90.] >, < Timestep 1 with unit cell dimensions [ 0.  0.  0. 90. 90. 90.] >, < Timestep 0 with unit cell dimensions [ 0.  0.  0. 90. 90. 90.] >]
['aux', 'copy', 'copy_slice', 'data', 'dimensions', 'dt', 'forces', 'frame', 'from_coordinates', 'from_timestep', 'has_forces', 'has_positions', 'has_velocities', 'n_atoms', 'order', 'positions', 'time', 'triclinic_dimensions', 'velocities', 'volume']
Frame:     0, Time:    1.000 ps
Rgyr: 16.669 A
Frame:    20, Time:   21.000 ps
Rgyr: 17.1491 A
Frame:    40, Time:   41.000 ps
Rgyr: 17.9416 A
Frame:    60, Time:   61.000 ps
Rgyr: 18.8433 A
Frame:    80, Time:   81.000 ps
Rgyr: 19.4571 A


In [20]:
## MDTraj
# Subset for trajectory
print (t[:3])
#print (u[:3]) #In MDAnalysis not work
print (t[-1])
print (t.xyz.shape)
print (t.time[0:10])
print (t.n_frames)

for tts in t[::20]:    
    print(tts)
    #print("Rgyr: {0:g} A".format(u.atoms.radius_of_gyration()))

<mdtraj.Trajectory with 3 frames, 3341 atoms, 214 residues, without unitcells>
<mdtraj.Trajectory with 1 frames, 3341 atoms, 214 residues, without unitcells>
(98, 3341, 3)
[0 1 2 3 4 5 6 7 8 9]
98
<mdtraj.Trajectory with 1 frames, 3341 atoms, 214 residues, without unitcells>
<mdtraj.Trajectory with 1 frames, 3341 atoms, 214 residues, without unitcells>
<mdtraj.Trajectory with 1 frames, 3341 atoms, 214 residues, without unitcells>
<mdtraj.Trajectory with 1 frames, 3341 atoms, 214 residues, without unitcells>
<mdtraj.Trajectory with 1 frames, 3341 atoms, 214 residues, without unitcells>


## Trajectories saving

In [49]:
## MDAnalysis
import MDAnalysis
from MDAnalysis.tests.datafiles import PDB, XTC
u2 = MDAnalysis.Universe(PDB, XTC)
protein = u2.select_atoms("protein")
with MDAnalysis.Writer("protein.xtc", protein.n_atoms) as W:
    for ts in u2.trajectory:
        W.write(protein)

/Users/alsalas/anaconda3/lib/python3.6/site-packages/MDAnalysis/lib/mdamath.py:69: RuntimeWarning: invalid value encountered in sqrt
  return np.sqrt(np.dot(v, v))
/Users/alsalas/anaconda3/lib/python3.6/site-packages/MDAnalysis/lib/mdamath.py:228: RuntimeWarning: invalid value encountered in float_scalars
  B[2][1] = z * (np.cos(a) - np.cos(b) * np.cos(c)) / np.sin(c)
/Users/alsalas/anaconda3/lib/python3.6/site-packages/MDAnalysis/lib/mdamath.py:152: RuntimeWarning: invalid value encountered in arccos
  angle = np.arccos(np.dot(a, b) / (norm(a) * norm(b)))
/Users/alsalas/anaconda3/lib/python3.6/site-packages/MDAnalysis/lib/mdamath.py:229: RuntimeWarning: invalid value encountered in sqrt
  B[2][2] = np.sqrt(z * z - B[2][0] ** 2 - B[2][1] ** 2)
/Users/alsalas/anaconda3/lib/python3.6/site-packages/MDAnalysis/lib/mdamath.py:152: RuntimeWarning: invalid value encountered in float_scalars
  angle = np.arccos(np.dot(a, b) / (norm(a) * norm(b)))
/Users/alsalas/anaconda3/lib/python3.6/site-pac

In [23]:
## MDTraj
# the hdf5 format stores the topology inside the file for convenience
t[::2].save('halftraj.h5')

# the format will be parsed based on the extension, or you can call the
# format-specific save methods
t[0:10].save_dcd('first-ten-frames.dcd')

# Trajectory with specific subset of atoms
atoms_to_keep = [a.index for a in t.topology.atoms if a.name == 'CA']
t.restrict_atoms(atoms_to_keep)  # this acts inplace on the trajectory
t.save('CA-only.h5')

## Selecciones

In [54]:
## MDAnalysis
print('How many atoms?    %s' % len(u.atoms))
print('How many residues? %s' % len(u.residues))

## MDAnalysis
CA = u.select_atoms("protein")
pprint.pprint(CA)
acidic = CA.select_atoms("resname ASP or resname GLU")
pprint.pprint(list(acidic.residues)[:3])
residues = u.select_atoms("around 4.0 resid 22").residues
pprint.pprint(list(residues))

How many atoms?    3341
How many residues? 214
<AtomGroup with 3341 atoms>
[<Residue GLU, 22>, <Residue ASP, 33>, <Residue GLU, 44>]
[<Residue GLN, 18>,
 <Residue PHE, 19>,
 <Residue ILE, 20>,
 <Residue MET, 21>,
 <Residue LYS, 23>,
 <Residue TYR, 24>,
 <Residue GLY, 25>,
 <Residue ARG, 206>]


In [55]:
## MDTraj
print('How many atoms?    %s' % t.n_atoms)
print('How many residues? %s' % t.n_residues)

frame_idx = 4 # zero indexed frame number
atom_idx = 9 # zero indexed atom index
print('Where is the fifth atom at the tenth frame?')
print('x: %s\ty: %s\tz: %s' % tuple(t.xyz[frame_idx, atom_idx,:]))

## MDTraj
print(topology.select('resid 1 to 2'))
print(topology.select('name N and backbone')[:3])

selection = topology.select_expression('name CA and resid 1 to 2')
print(selection)

How many atoms?    3341
How many residues? 214
Where is the fifth atom at the tenth frame?
x: 1.062337	y: 1.0965732	z: -0.7430963
[19 20 21 ... 59 60 61]
[ 0 19 43]
[atom.index for atom in topology.atoms if ((atom.name == 'CA') and (1 <= atom.residue.index <= 2))]


In [56]:
## PyTraj
#supposed we want to keep 100 closest solvents around protein
p2 = mdp.load_sample_data('tz2')

print([res.name for res in p.top.residues 
       if not res.is_solvent()][:5])

new_traj = mdp.closest(p2, mask=':1-13', n_solvents=100, dtype='trajectory')
print(new_traj)

['MET', 'ARG', 'ILE', 'ILE', 'LEU']
pytraj.Trajectory, 10 frames: 
Size: 0.000116 (GB)
<Topology: 520 atoms, 113 residues, 101 mols, PBC with box type = ortho>
           
